### PR TITLE
Fixes frontend and backend build

### LINKED ISSUE #1: Both backend and front builds failed
I'm trying this using the latest commit `4976f1efe889a67ec8d657bc20e6e4631a3a05d2` on OSX 10.14.1.

The frontend is failing with:
```
  We've found a bug for you!
  ~/reason-graphql-experiment/src/client/editor.re
  
  Some fatal warnings were triggered (4 occurrences)
  
    at Array.map (<anonymous>)tions.cmj

error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c node scripts/build.js
Directory: ~/reason-graphql-experiment
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "~/reason-graphql-experiment/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The backend is failing on the `esy @server` command:
```
info building @opam/ocaml-migrate-parsetree@1.1.0: starting
error: build failed
  build log:
    # esy-build-package: building: @opam/biniou@1.2.0
    # esy-build-package: running: 'jbuilder' 'build' '-p' 'biniou' '-j' '4'
          ocamlc src/.biniou.objs/bi_io.{cmo,cmt} (exit 2)
    (cd _build/default && ~/.esy/3________________________________________________________________/i/ocaml-4.7.1003-3887ca7b/bin/ocamlc.opt -safe-string -g -bin-annot -I src/.biniou.objs -I src/.biniou.objs/.private -I /usr/local/lib/node_modules/reason-cli/r/3____________________________________________/i/opam__slash__easy_format-1.3.0-4483f5bb/lib/easy-format -intf-suffix .ml -no-alias-deps -o src/.biniou.objs/bi_io.cmo -c -impl src/bi_io.ml)
    File "src/bi_io.ml", line 1:
    Error: /usr/local/lib/node_modules/reason-cli/r/3____________________________________________/i/opam__slash__easy_format-1.3.0-4483f5bb/lib/easy-format/easy_format.cmi
    is not a compiled interface for this version of OCaml.
    It seems to be for an older version of OCaml.
        ocamlopt src/.biniou.objs/bi_io.{cmx,o} (exit 2)
    (cd _build/default && ~/.esy/3________________________________________________________________/i/ocaml-4.7.1003-3887ca7b/bin/ocamlopt.opt -safe-string -g -I src/.biniou.objs -I src/.biniou.objs/.private -I /usr/local/lib/node_modules/reason-cli/r/3____________________________________________/i/opam__slash__easy_format-1.3.0-4483f5bb/lib/easy-format -intf-suffix .ml -no-alias-deps -o src/.biniou.objs/bi_io.cmx -c -impl src/bi_io.ml)
    File "src/bi_io.ml", line 1:
    Error: /usr/local/lib/node_modules/reason-cli/r/3____________________________________________/i/opam__slash__easy_format-1.3.0-4483f5bb/lib/easy-format/easy_format.cmi
    is not a compiled interface for this version of OCaml.
    It seems to be for an older version of OCaml.
    error: command failed: 'jbuilder' 'build' '-p' 'biniou' '-j' '4'
    esy-build-package: exiting with errors above...
    
  building @opam/biniou@1.2.0
esy: exiting due to errors above
```

I do have ocaml installed, could that be an issue? But I thought esy manages its own version of ocaml?

(It first failed because libev wasn't installed. Fixed that by installing via brew and then setting 
`export C_INCLUDE_PATH=/usr/local/include` and `export LIBRARY_PATH=/usr/local/`.)

### PR DESCRIPTION
**Pull request by cem2ran**
I found that I had to run `esy @server` to install native dependencies. Should resolve #1

### CODE REVIEW

**Comment by anmonteiro** [comment]
Looks good. Can you generate the static assets with `yarn build` too? We deploy the artifacts in the build dir to `now.sh` directly.

**Comment by cem2ran** [comment]
@anmonteiro only build/static or build/*

Here's the changes triggered by build. Let me know if anything needs to be .gitignored:

```
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   build/asset-manifest.json
        modified:   build/index.html
        deleted:    build/precache-manifest.730680669be6a379bc86a5d7964a5e00.js
        modified:   build/service-worker.js
        deleted:    build/static/css/main.8f4013c0.chunk.css
        deleted:    build/static/css/main.8f4013c0.chunk.css.map
        deleted:    build/static/js/main.8eb553a6.chunk.js
        deleted:    build/static/js/main.8eb553a6.chunk.js.map

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        build/precache-manifest.94ac940fbf1e33c7f7487b9c116e310d.js
        build/static/css/main.87b7ddfa.chunk.css
        build/static/css/main.87b7ddfa.chunk.css.map
        build/static/js/main.62feaae2.chunk.js
        build/static/js/main.62feaae2.chunk.js.map
```

**Comment by anmonteiro** [comment]
@cem2ran nope, those are fine to commit. thanks

**Comment by anmonteiro** [comment]
Thanks.

**Pull request merged**
